// Strings for the pause menu, save/load and help screens (merged into STRINGS in strings.js).
export const EXTRA = {
  uk: {
    level_l11: 'ВУЛИЦЯ І ПАРК ШЕВЧЕНКА',
    menu_continue: 'ПРОДОВЖИТИ', menu_save: 'ЗБЕРЕГТИ ГРУ', menu_load: 'ЗАВАНТАЖИТИ', menu_help: 'ДОВІДКА',
    pause_resume: 'ПРОДОВЖИТИ', pause_quit: 'ГОЛОВНЕ МЕНЮ', back: 'НАЗАД',
    save_note: 'Збереження фіксує початок поточного рівня (рахунок, хабарі, корумпованість, життя).',
    load_note: 'Автозбереження робиться на початку кожного рівня.',
    slot_auto: 'АВТО', slot: 'СЛОТ', slot_empty: 'порожньо', saved: 'ЗБЕРЕЖЕНО', save_failed: 'НЕ ВДАЛОСЯ ЗБЕРЕГТИ',
    help_footer: '← → сторінки   ESC — закрити',
    help_title_controls: 'КЕРУВАННЯ', help_title_legend: 'ЩО Є ЩО',
    help_move: 'рух', help_jump: 'стрибок (тримай — вище)', help_bribe: 'кинути хабар (коштує гроші)',
    help_pr: 'чорний PR — лякає журналістів', help_interact: 'дія: потрусити каштан, люк, гості', help_pause: 'пауза: зберегти / завантажити',
    help_restart: 'почати з контрольної точки', help_mute: 'звук увімк./вимк.', help_help: 'ця довідка',
    help_rules: 'Кожна монета — це «подяка»: росте КОРУМПОВАНІСТЬ, з’являються журналісти й детективи НАБУ, мости падають швидше. '
      + 'Не бери нічого — і на виборах тебе переоберуть. Хабар спрацьовує не завжди, а невдалий хабар додає корумпованості.',
    help_coin: 'Монета: +1 хабар. Деякі — мічені купюри: з люка вилізе детектив.',
    help_bag: 'Мішок: +10 хабарів і багато корумпованості.',
    help_qblock: 'Блок «?»: вдар знизу — випаде монета.',
    help_journalist: 'Журналіст: спалах камери оглушує. Боїться чорного PR. Хабар — 22%.',
    help_detective: 'Детектив НАБУ: переслідує, кидає повістки. Хабар — лише 14%.',
    help_cop: 'Патрульний: бере хабар завжди, але зіткнення болить.',
    help_manhole: 'Люк: звідси виходять детективи.',
    help_checkpoint: 'Прапор: контрольна точка.',
    help_heat: 'Корумпованість: 0% — чистий. Від 55% потяг на Захід уже не доїде.',
    help_pipes: 'Труби, смітники, дахи зупинок, балкони — на них можна стати.',
  },
  en: {
    level_l11: 'STREET & SHEVCHENKO PARK',
    menu_continue: 'CONTINUE', menu_save: 'SAVE GAME', menu_load: 'LOAD GAME', menu_help: 'HELP',
    pause_resume: 'RESUME', pause_quit: 'MAIN MENU', back: 'BACK',
    save_note: 'A save stores the start of the current level (score, bribes, corruption, lives).',
    load_note: 'An autosave is written at the start of every level.',
    slot_auto: 'AUTO', slot: 'SLOT', slot_empty: 'empty', saved: 'SAVED', save_failed: 'SAVE FAILED',
    help_footer: '← → pages   ESC — close',
    help_title_controls: 'CONTROLS', help_title_legend: 'WHAT IS WHAT',
    help_move: 'move', help_jump: 'jump (hold for higher)', help_bribe: 'throw a bribe (costs money)',
    help_pr: 'black PR — scares journalists', help_interact: 'interact: shake a tree, hatch, guests', help_pause: 'pause: save / load',
    help_restart: 'restart from checkpoint', help_mute: 'sound on/off', help_help: 'this help',
    help_rules: 'Every coin is a “thank-you”: CORRUPTION rises, journalists and NABU detectives appear, bridges fall faster. '
      + 'Take nothing and the voters re-elect you. Bribes do not always work, and a failed bribe adds corruption.',
    help_coin: 'Coin: +1 bribe. Some are marked bills: a detective climbs out of a manhole.',
    help_bag: 'Money bag: +10 bribes and a lot of corruption.',
    help_qblock: '“?” block: hit it from below to pop a coin.',
    help_journalist: 'Journalist: the camera flash stuns you. Afraid of black PR. Bribe odds 22%.',
    help_detective: 'NABU detective: chases you and throws warrants. Bribe odds only 14%.',
    help_cop: 'Patrol officer: always takes a bribe, but bumping into him hurts.',
    help_manhole: 'Manhole: detectives come out of these.',
    help_checkpoint: 'Flag: checkpoint.',
    help_heat: 'Corruption: 0% is clean. From 55% the train West never arrives.',
    help_pipes: 'Pipes, bins, bus-stop roofs and balconies can be stood on.',
  },
};
