import { EXTRA } from './strings_extra.js';
import { W2 } from './strings_w2.js';
import { W3 } from './strings_w3.js';

// All player-facing text. Keys are shared between languages; `t(key)` picks the active one.
export const STRINGS = {
  uk: {
    title: 'СЛУГА БЮДЖЕТУ',
    subtitle: 'Сатиричний платформер про ціну корупції',
    press_start: 'НАТИСНИ ENTER',
    menu_start: 'ПОЧАТИ КАМПАНІЮ',
    menu_lang: 'МОВА: УКР',
    menu_best: 'НАЙКРАЩИЙ РЕЗУЛЬТАТ',
    menu_none: 'ще не було виборів',
    menu_controls: '← → рух   SPACE стрибок   J хабар   K каштан   L компромат   E дія   P пауза   M звук',
    menu_hint: 'Не збирай гроші — і тебе переоберуть. Збирай — і побачиш, як падають мости.',
    dev_mode: 'DEV: 1-9 рівень  H+/H- корумпованість  F фінал',

    hud_score: 'РАХУНОК', hud_lives: 'ЖИТТЯ', hud_bribes: 'ХАБАРІ', hud_level: 'РІВЕНЬ', hud_time: 'ЧАС',
    hud_clean: 'ЧИСТИЙ', hud_heat: 'КОРУМПОВАНІСТЬ', hud_conscience: 'СУМЛІННЯ', hud_rep: 'РЕПУТАЦІЯ', hud_rep_good: 'ДОБРА', hud_rep_mid: 'ПІДМОЧЕНА', hud_rep_low: 'НА ДНІ', hud_cons_calm: 'СПОКІЙНЕ', hud_cons_uneasy: 'НЕСПОКІЙНЕ', hud_cons_bite: 'ГРИЗЕ!',
    tier_clean: 'ЧИСТИЙ', tier_suspicious: 'ПІДОЗРІЛИЙ', tier_investigated: 'ПІД СЛІДСТВОМ',
    tier_wanted: 'У РОЗШУКУ', tier_raid: 'ОБШУК НАБУ',

    level_l11: 'ВУЛИЦЯ КИЄВА', level_l12: 'МІСТ ЧЕРЕЗ ДНІПРО', level_l21: 'ВЕРХОВНА РАДА',
    level_l22: 'ЗУСТРІЧ З ВИБОРЦЯМИ', level_l31: 'ЗАКРИТА ВЕЧІРКА', level_l32: 'АЕРОПОРТ',
    world_1: 'СВІТ 1: КИЇВ', world_2: 'СВІТ 2: ВЛАДА', world_3: 'СВІТ 3: ПАДІННЯ',

    sign_bridges: 'МОСТИ — НЕ ДЛЯ ВСІХ.', sign_facts: 'FACTS HURT.', sign_reform: 'РЕФОРМА — ЦЕ ТИМЧАСОВО!',
    sign_nabu: 'АНТИКОРУПЦІЙНЕ БЮРО', sign_rada: 'СЛУГИ НАРОДУ', sign_voters: 'ЗУСТРІЧ З ВИБОРЦЯМИ',
    sign_party: 'ЗАКРИТИЙ ЗАХІД', sign_airport: 'ВИЛІТ',

    bubble_journalist_spot: 'Коментар для преси?', bubble_journalist_bribed: '…без коментарів.',
    bubble_journalist_flee: 'Джинса! Тікаю!', bubble_journalist_refuse: 'Це на першу шпальту!',
    bubble_detective_spot: 'НАБУ! Стояти!', bubble_detective_bribed: 'Я нічого не бачив.',
    bubble_detective_refuse: 'Це — хабар. Протокол!', bubble_detective_emerge: 'Це була мічена купюра!',
    bubble_cop_bribed: 'Проїжджайте!', bubble_voter_angry: 'Де дороги?!', bubble_voter_bribed: 'Ну добре… гречка.',
    bubble_voter_calm: 'Наш кандидат!', bubble_guest_offer: 'Візьми, не соромся!',
    bubble_guard_demand: 'Паспорт… і конверт.', bubble_guard_free: 'Гарного відпочинку!',
    bubble_guard_arrest: 'Ви затримані.',

    level_start: 'РІВЕНЬ', level_clear: 'РІВЕНЬ ПРОЙДЕНО', level_bonus: 'БОНУС', honest_bonus: 'ЧИСТІ РУКИ',
    checkpoint: 'КОНТРОЛЬНА ТОЧКА', time_up: 'ЧАС ВИЙШОВ', lost_life: 'ЖИТТЯ ВТРАЧЕНО',
    bribe_ok: 'ХАБАР ПРИЙНЯТО', bribe_fail: 'ВІДМОВА! +КОРУМПОВАНІСТЬ', no_money: 'НЕМАЄ ГРОШЕЙ',
    trap: 'МІЧЕНА КУПЮРА!', raid: 'ОБШУК!', paused: 'ПАУЗА',
    hurt_journalist: 'ЖУРНАЛІСТ!', hurt_detective: 'ДЕТЕКТИВ НАБУ!', hurt_cop: 'ПОЛІЦІЯ!', hurt_voter: 'ВИБОРЕЦЬ!',
    hurt_warrant: 'ПІДОЗРА!', hurt_jar: 'БАНКА!', hurt_hook: 'ГАК!', hurt_hit: 'УДАР!',
    die_spike: 'ШИПИ!', die_water: 'У ВОДУ!', die_pit: 'ПРІРВА!', die_time: 'ЧАС ВИЙШОВ', die_reputation: 'РЕПУТАЦІЮ ЗНИЩЕНО!', life_pop: '+1 ЖИТТЯ', life_letter_flash: 'АПТЕЧКА: +1 ЖИТТЯ!', stash_found: 'ЩОСЬ ЗНАЙШЛОСЯ…', hint_stash: 'E — ОБШУКАТИ', life_score_flash: 'ВИБОРЦІ ЦІНУЮТЬ: +1 ЖИТТЯ!',

    story_intro_1: 'Київ. Передвиборча кампанія. Ти — народний депутат, і бюджет лежить просто на дорозі.',
    story_intro_2: 'Кожна монета — це «подяка». Кожна подяка — це журналіст за спиною і детектив НАБУ попереду.',
    story_intro_3: 'Або… не бери нічого. Пройди весь шлях чистим — і народ тебе переобере.',
    story_w2: 'Світ 2. Влада. Маріїнський парк, каштани — і Верховна Рада, де голосують кнопками, а б’ються регламентом.',
    story_w3: 'Світ 3. Падіння. Вечірка на Печерську, потім — Бориспіль. Куди летимо?',
    story_honest_1: 'Ти не взяв жодної копійки. Два тижні тиші: вода, книга, жодного дзвінка з «прохачами».',
    story_honest_2: 'Повернення. На вокзалі — не охорона й не журналісти, а виборці: з квітами, прапорцями і «Дякуємо!».',
    story_honest_3: 'Ніч виборів. 61% — і жодного компромату. Тебе переобрали.',
    story_escape_1: 'Приватний борт, три валізи готівки, паспорт іншої країни.',
    story_escape_2: 'Вілла з видом на море. Але кожен дзвінок у двері звучить як «НАБУ! Відчиніть».',
    story_escape_3: 'Ти втік. Поки що. Заочно — 12 років.',
    story_arrest_1: 'Трап літака. Двоє в плащах: «Пане депутате, ваш рейс скасовано».',
    story_arrest_2: 'Суд. Камери журналістів. Тепер факти справді болять.',
    story_gameover: 'Кампанія провалена. Мости впали, гроші закінчилися, виборці пам’ятають.',
    ending_honest: 'ПЕРЕОБРАНО', ending_escape: 'ВТЕЧА (ПОКИ ЩО)', ending_arrest: 'ЗАТРИМАНО НАБУ',
    ending_gameover: 'ГРУ ЗАКІНЧЕНО',
    result_score: 'РАХУНОК', result_corruption: 'ЗІБРАНО', result_time: 'ЧАС', play_again: 'ENTER — ГРАТИ ЗНОВУ',
    skip_hint: 'SPACE — далі',
    goal_hint: 'ВИХІД →',
  },
  en: {
    title: 'SERVANT OF THE BUDGET',
    subtitle: 'A satirical platformer about the price of corruption',
    press_start: 'PRESS ENTER',
    menu_start: 'START CAMPAIGN',
    menu_lang: 'LANG: ENG',
    menu_best: 'BEST RESULT',
    menu_none: 'no election yet',
    menu_controls: '← → move   SPACE jump   J bribe   K chestnut   L kompromat   E act   P pause   M sound',
    menu_hint: 'Collect nothing and get re-elected. Collect coins and watch the bridges fall.',
    dev_mode: 'DEV: 1-9 level  H+/H- corruption  F finale',

    hud_score: 'SCORE', hud_lives: 'LIVES', hud_bribes: 'BRIBES', hud_level: 'LEVEL', hud_time: 'TIME',
    hud_clean: 'CLEAN', hud_heat: 'CORRUPTION', hud_conscience: 'CONSCIENCE', hud_rep: 'REPUTATION', hud_rep_good: 'GOOD', hud_rep_mid: 'TARNISHED', hud_rep_low: 'IN TATTERS', hud_cons_calm: 'CALM', hud_cons_uneasy: 'UNEASY', hud_cons_bite: 'GNAWING!',
    tier_clean: 'CLEAN', tier_suspicious: 'SUSPICIOUS', tier_investigated: 'INVESTIGATED',
    tier_wanted: 'WANTED', tier_raid: 'NABU RAID',

    level_l11: 'KYIV STREET', level_l12: 'DNIPRO BRIDGE', level_l21: 'PARLIAMENT',
    level_l22: 'MEETING THE VOTERS', level_l31: 'PRIVATE PARTY', level_l32: 'AIRPORT',
    world_1: 'WORLD 1: KYIV', world_2: 'WORLD 2: POWER', world_3: 'WORLD 3: THE FALL',

    sign_bridges: 'BRIDGES ARE FOR SOME PEOPLE.', sign_facts: 'FACTS HURT.', sign_reform: 'REFORM IS TEMPORARY!',
    sign_nabu: 'ANTI CORRUPTION BUREAU', sign_rada: 'SERVANTS OF THE PEOPLE', sign_voters: 'MEET YOUR CANDIDATE',
    sign_party: 'PRIVATE EVENT', sign_airport: 'DEPARTURES',

    bubble_journalist_spot: 'A comment for the press?', bubble_journalist_bribed: '…no comment.',
    bubble_journalist_flee: 'Smear piece! Run!', bubble_journalist_refuse: 'Front page!',
    bubble_detective_spot: 'NABU! Freeze!', bubble_detective_bribed: 'I saw nothing.',
    bubble_detective_refuse: 'That is a bribe. Noted!', bubble_detective_emerge: 'That was a marked bill!',
    bubble_cop_bribed: 'Move along!', bubble_voter_angry: 'Where are the roads?!', bubble_voter_bribed: 'Fine… buckwheat.',
    bubble_voter_calm: 'Our candidate!', bubble_guest_offer: 'Take it, don’t be shy!',
    bubble_guard_demand: 'Passport… and the envelope.', bubble_guard_free: 'Enjoy your vacation!',
    bubble_guard_arrest: 'You are under arrest.',

    level_start: 'LEVEL', level_clear: 'LEVEL CLEAR', level_bonus: 'BONUS', honest_bonus: 'CLEAN HANDS',
    checkpoint: 'CHECKPOINT', time_up: 'TIME UP', lost_life: 'LIFE LOST',
    bribe_ok: 'BRIBE ACCEPTED', bribe_fail: 'REFUSED! +CORRUPTION', no_money: 'NO MONEY',
    trap: 'MARKED BILL!', raid: 'RAID!', paused: 'PAUSED',
    hurt_journalist: 'JOURNALIST!', hurt_detective: 'NABU DETECTIVE!', hurt_cop: 'POLICE!', hurt_voter: 'VOTER!',
    hurt_warrant: 'SUSPICION NOTICE!', hurt_jar: 'JAR!', hurt_hook: 'HOOK!', hurt_hit: 'HIT!',
    die_spike: 'SPIKES!', die_water: 'INTO THE WATER!', die_pit: 'THE PIT!', die_time: 'TIME UP', die_reputation: 'REPUTATION RUINED!', life_pop: '+1 LIFE', life_letter_flash: 'FIRST-AID KIT: +1 LIFE!', stash_found: 'SOMETHING TURNED UP…', hint_stash: 'E — SEARCH', life_score_flash: 'THE VOTERS APPRECIATE IT: +1 LIFE!',

    story_intro_1: 'Kyiv. Election season. You are a member of parliament and the budget is lying on the road.',
    story_intro_2: 'Every coin is a “thank you”. Every thank-you brings a journalist behind you and a NABU detective ahead.',
    story_intro_3: 'Or… take nothing. Reach the airport clean and the people will re-elect you.',
    story_w2: 'World 2. Power. Mariinsky Park, chestnuts — and the Verkhovna Rada, where they vote with buttons and fight with the rules of procedure.',
    story_w3: 'World 3. The fall. A party in Pechersk, then Boryspil airport. Where are we flying?',
    story_honest_1: 'Not a single coin taken. Two weeks of silence: water, a book, no calls from “petitioners”.',
    story_honest_2: 'The return. At the station there are no guards and no journalists — just voters, with flowers, little flags and “Thank you!”.',
    story_honest_3: 'Election night. 61% and zero dirt. Re-elected.',
    story_escape_1: 'A private jet, three suitcases of cash, a second passport.',
    story_escape_2: 'A villa by the sea. But every doorbell sounds like “NABU! Open up”.',
    story_escape_3: 'You escaped. For now. Sentenced in absentia: 12 years.',
    story_arrest_1: 'The boarding stairs. Two men in trench coats: “Sir, your flight is cancelled.”',
    story_arrest_2: 'Court. Cameras everywhere. Now the facts really hurt.',
    story_gameover: 'Campaign failed. The bridges fell, the money ran out, the voters remember.',
    ending_honest: 'RE-ELECTED', ending_escape: 'ESCAPED (FOR NOW)', ending_arrest: 'ARRESTED BY NABU',
    ending_gameover: 'GAME OVER',
    result_score: 'SCORE', result_corruption: 'COLLECTED', result_time: 'TIME', play_again: 'ENTER — PLAY AGAIN',
    skip_hint: 'SPACE — next',
    goal_hint: 'EXIT →',
  },
};

for (const lang of Object.keys(EXTRA)) Object.assign(STRINGS[lang], EXTRA[lang]);
for (const lang of Object.keys(W2)) Object.assign(STRINGS[lang], W2[lang]);
for (const lang of Object.keys(W3)) Object.assign(STRINGS[lang], W3[lang]);
