// Strings for the pause menu, save/load and help screens (merged into STRINGS in strings.js).
export const EXTRA = {
  uk: {
    // briefing before 1-1 (scenes/Briefing.js)
    brief_title: 'ІНСТРУКТАЖ ДЛЯ НАРОДНОГО ДЕПУТАТА',
    brief_keys: 'КЕРУВАННЯ',
    brief_rules: 'ЯК ТУТ УСЕ ВЛАШТОВАНО',
    brief_move: 'рух', brief_jump: 'стрибок (тримай — вище)', brief_nut: 'каштан: оглушує, безкоштовно',
    brief_pr: 'компромат: журналісти тікають', brief_bribe: 'хабар: гроші вирішують питання',
    brief_act: 'дія: потрусити каштан, люк, кіоск', brief_pause: 'пауза, збереження, довідка',
    brief_t_move: 'рух', brief_t_jump: 'стрибок', brief_t_nut: 'каштан', brief_t_pr: 'компромат',
    brief_t_bribe: 'хабар', brief_t_act: 'дія', brief_t_pause: 'пауза',
    brief_r1: 'Київ щедрий: монети, мішки й «подяки» чекають на кожному кроці. Брати чи ні — питання твоєї совісті.',
    brief_rep: 'РЕПУТАЦІЯ — твоє здоров’я. Кийки, спалахи камер, пляшки й підозри її псують; на нулі — мінус життя. Посидь тихо — і вона відновиться. Життя повертають аптечки: вони сховані в коробках (E — обшукати) і трапляються в блоках «?». А ще — добрий рахунок.',
    brief_r2: 'КОРУМПОВАНІСТЬ показує, наскільки ти «успішний». Поруч — СУМЛІННЯ: гризе за погані вчинки, а переповнене паралізує каяттям на кілька секунд. Кажуть, алкоголь його глушить. Ненадовго.',
    brief_r3: 'Каштани ростуть на деревах і нічого не коштують. Мабуть, тому їх ніхто не декларує.',
    brief_r4: 'Всесвіт, звісно, не веде бухгалтерії. Але кажуть, що карма існує. І наслідки — теж. Чутки, мабуть.',
    brief_go: 'ENTER / ТОРКНИСЬ — ДО РОБОТИ!',
    level_l11: 'ВУЛИЦЯ І ПАРК ШЕВЧЕНКА',
    menu_continue: 'ПРОДОВЖИТИ', menu_save: 'ЗБЕРЕГТИ ГРУ', menu_load: 'ЗАВАНТАЖИТИ', menu_help: 'ДОВІДКА',
    pause_resume: 'ПРОДОВЖИТИ', pause_quit: 'ГОЛОВНЕ МЕНЮ', back: 'НАЗАД',
    save_note: 'Збереження фіксує початок поточного рівня (рахунок, хабарі, корумпованість, життя).',
    load_note: 'Автозбереження робиться на початку кожного рівня.',
    slot_auto: 'АВТО', slot: 'СЛОТ', slot_empty: 'порожньо', saved: 'ЗБЕРЕЖЕНО', save_failed: 'НЕ ВДАЛОСЯ ЗБЕРЕГТИ',
    help_footer: '← → сторінки   ESC — закрити',
    help_title_controls: 'КЕРУВАННЯ', help_title_legend: 'ЩО Є ЩО',
    help_move: 'рух', help_jump: 'стрибок (тримай — вище)', help_bribe: 'кинути хабар (коштує гроші)',
    help_pr: 'компромат — журналісти тікають від нього', help_interact: 'дія: потрусити каштан, люк, гості', help_pause: 'пауза: зберегти / завантажити',
    help_restart: 'почати з контрольної точки', help_mute: 'звук увімк./вимк.', help_help: 'ця довідка',
    help_rules: 'Кожна монета — це «подяка». Брати чи ні — справа совісті. Кажуть, карма існує. І наслідки — теж. '
      + 'Не бери нічого — і, можливо, виборці це оцінять. Хабар спрацьовує не завжди.',
    help_coin: 'Монета: +1 хабар. Деякі — мічені купюри: з люка вилізе детектив.',
    help_bag: 'Мішок: +10 хабарів і багато корумпованості.',
    help_qblock: 'Блок «?»: вдар знизу — випаде монета.',
    help_journalist: 'Журналіст: спалах камери оглушує. Боїться компромату. Хабар — 22%.',
    help_detective: 'Детектив НАБУ: переслідує, вручає підозри. Хабар — лише 14%.',
    help_cop: 'Патрульний: бере хабар завжди, але зіткнення болить.',
    help_manhole: 'Люк: звідси виходять детективи.',
    help_checkpoint: 'Прапор: контрольна точка.',
    help_heat: 'Корумпованість: 0% — чистий. Що буде від 55% — дізнаєшся сам.',
    help_pipes: 'Труби, смітники, дахи зупинок, балкони — на них можна стати.',
  },
  en: {
    brief_title: 'BRIEFING FOR A PEOPLE’S DEPUTY',
    brief_keys: 'CONTROLS',
    brief_rules: 'HOW THINGS WORK HERE',
    brief_move: 'move', brief_jump: 'jump (hold for higher)', brief_nut: 'chestnut: stuns, free of charge',
    brief_pr: 'kompromat: journalists run away', brief_bribe: 'bribe: money solves problems',
    brief_act: 'act: shake a tree, a hatch, a kiosk', brief_pause: 'pause, save, help',
    brief_t_move: 'move', brief_t_jump: 'jump', brief_t_nut: 'chestnut', brief_t_pr: 'kompromat',
    brief_t_bribe: 'bribe', brief_t_act: 'act', brief_t_pause: 'pause',
    brief_r1: 'Kyiv is generous: coins, money bags and "thank-yous" wait at every corner. To take or not to take is a matter of conscience.',
    brief_rep: 'REPUTATION is your health. Batons, camera flashes, bottles and suspicion notices tarnish it; at zero you lose a life. Keep a low profile and it recovers. Lives come back with first-aid kits: hidden in boxes (E to search) and sometimes in “?” blocks. And with a good score.',
    brief_r2: 'CORRUPTION shows how "successful" you are. Next to it is CONSCIENCE: it gnaws at you for bad deeds, and when it overflows, remorse freezes you for a few seconds. They say alcohol silences it. Briefly.',
    brief_r3: 'Chestnuts grow on trees and cost nothing. Probably why nobody declares them.',
    brief_r4: 'The universe, of course, keeps no books. But they say karma exists. And consequences too. Just rumours, probably.',
    brief_go: 'ENTER / TAP — GET TO WORK!',
    level_l11: 'STREET & SHEVCHENKO PARK',
    menu_continue: 'CONTINUE', menu_save: 'SAVE GAME', menu_load: 'LOAD GAME', menu_help: 'HELP',
    pause_resume: 'RESUME', pause_quit: 'MAIN MENU', back: 'BACK',
    save_note: 'A save stores the start of the current level (score, bribes, corruption, lives).',
    load_note: 'An autosave is written at the start of every level.',
    slot_auto: 'AUTO', slot: 'SLOT', slot_empty: 'empty', saved: 'SAVED', save_failed: 'SAVE FAILED',
    help_footer: '← → pages   ESC — close',
    help_title_controls: 'CONTROLS', help_title_legend: 'WHAT IS WHAT',
    help_move: 'move', help_jump: 'jump (hold for higher)', help_bribe: 'throw a bribe (costs money)',
    help_pr: 'kompromat — journalists run from it', help_interact: 'interact: shake a tree, hatch, guests', help_pause: 'pause: save / load',
    help_restart: 'restart from checkpoint', help_mute: 'sound on/off', help_help: 'this help',
    help_rules: 'Every coin is a “thank-you”. To take or not is a matter of conscience. They say karma exists. And consequences too. '
      + 'Take nothing and the voters might appreciate it. Bribes do not always work.',
    help_coin: 'Coin: +1 bribe. Some are marked bills: a detective climbs out of a manhole.',
    help_bag: 'Money bag: +10 bribes and a lot of corruption.',
    help_qblock: '“?” block: hit it from below to pop a coin.',
    help_journalist: 'Journalist: the camera flash stuns you. Afraid of kompromat. Bribe odds 22%.',
    help_detective: 'NABU detective: chases you and serves suspicion notices. Bribe odds only 14%.',
    help_cop: 'Patrol officer: always takes a bribe, but bumping into him hurts.',
    help_manhole: 'Manhole: detectives come out of these.',
    help_checkpoint: 'Flag: checkpoint.',
    help_heat: 'Corruption: 0% is clean. What happens from 55% — you will find out.',
    help_pipes: 'Pipes, bins, bus-stop roofs and balconies can be stood on.',
  },
};
