// Strings for the chestnut campaign (world 2: Mariinsky park, bunker, Rada corridor, session hall).
// Merged into STRINGS in strings.js after strings_extra.js.
export const W2 = {
  uk: {
    drink_whiskey_pop: 'ВІСКІ!', drink_vodka_pop: 'ГОРІЛКА!', shop_price: 'Ціна:', hint_shop: 'E — купити віскі',
    help_title_conscience: 'СОВІСТЬ І АЛКОГОЛЬ',
    help_conscience: 'Сумління (шкала праворуч від корумпованості): росте від хабарів, мішків і поганих вчинків. На 100 — каяття паралізує на кілька секунд.',
    help_whiskey: 'Віскі: купити в кіоску (E, 3 хабарі) або знайти. Совість замовкає, але ти п’яний: повільніший, кидаєш криво.',
    help_vodka: 'Горілка (сховище): глушить совість майже повністю. Ноги заплітаються, світ хитається.',
    help_voice: 'Внутрішній голос коментує все, що ти робиш. Чим більше краде депутат, тим цинічніше він звучить.',
    help_angel: 'Ангел-совість: з’являється, коли каяття паралізує.',
    hud_nuts: 'КАШТАНИ',
    ammo_nut: 'каштан', ammo_book: '«Капітал»',
    no_nuts: 'Нема каштанів! Потрусіть каштан (E)',
    tree_empty: 'Каштан уже обтрусили',
    hint_tree: 'E — потрусити каштан',
    hint_secret: 'E — таємний люк?!',
    secret_found: 'ТАЄМНИЙ ХІД ДО СХОВИЩА!',
    boss_animator: 'АНІМАТОР У КОСТЮМІ ПАТРОНА', boss_ratboss: 'ЩУР-БАЛАЛАЄЧНИК', boss_speaker: 'СПІКЕР',
    boss_beaten: 'БОС ПЕРЕМОЖЕНИЙ!', boss_bribed: 'БОС… ДОМОВИВСЯ',
    goal_locked_animator: 'Аніматор не пускає до дверей!',
    goal_locked_ratboss: 'Щур охороняє вихід!',
    goal_locked_speaker: 'Спікер ще не закрив засідання!',
    level_p21: 'МАРІЇНСЬКИЙ ПАРК', level_p21b: 'СХОВИЩЕ ПІД РАДОЮ', level_p22: 'КОРИДОРИ РАДИ', level_p23: 'СЕСІЙНА ЗАЛА',
    sign_park: 'МАРІЇНСЬКИЙ ПАРК. КАШТАНИ НЕ ЗРИВАТИ!', sign_rada: 'ВХІД ЛИШЕ ДЛЯ ОБРАНИХ',
    sign_bunker: 'УКРИТТЯ №1 (1953)', sign_corridor: 'ТИХО! ЙДЕ ГОЛОСУВАННЯ', sign_hall: 'СЕСІЙНА ЗАЛА →',
    hurt_oldlady: 'Бабця палицею!', hurt_chestnut: 'Каштаном по лобі!', hurt_chocolate: 'Шоколадкою!',
    hurt_note: 'Фальшива нота!', hurt_papers: 'Законопроєктом по голові!', hurt_shockwave: 'Удар молотка!',
    hurt_rat: 'Щур вкусив!', hurt_oppmp: 'Опозиція штовхається!', hurt_animator: 'Обійми Патрона!',
    hurt_ratboss: 'Балалайкою!', hurt_speaker: 'Спікер навалився!',
    bubble_oldlady_strike: 'Ах ти ж злодюга!', bubble_oldlady_bribed: 'На пенсію… дякую, синку',
    bubble_oldlady_refuse: 'Мене не купиш!', bubble_oldlady_stunned: 'Ой-йой…',
    bubble_kid_mine: 'Мій каштан!', bubble_kid_bribed: 'Ура, на льодяник!', bubble_kid_refuse: 'Мало!',
    bubble_kid_stunned: 'Ай!',
    bubble_rat_bribed: 'Пі! Золото партії!', bubble_rat_refuse: 'Пі-пі!', bubble_rat_stunned: 'Пі…',
    bubble_oppmp_throw: 'Ганьба!', bubble_oppmp_bribed: 'Це… на партійні потреби',
    bubble_oppmp_refuse: 'Я не такий!', bubble_oppmp_stunned: 'Мій рейтинг!',
    bubble_seatedmp_bribed: 'Голосую «за»!', bubble_seatedmp_refuse: 'Проти!',
    bubble_assistant_hello: 'Депутат на нараді…', bubble_assistant_bribed: 'Я передам шефу!',
    bubble_animator_intro: 'Фото з Патроном — шість хабарів!', bubble_animator_beg: 'Гав! Скинемося на корм?',
    bubble_animator_bribed: 'Гав-гав! Проходьте!', bubble_animator_defeated: 'Все, зміна скінчилась…',
    bubble_animator_refuse: 'Замало на корм!',
    bubble_ratboss_intro: 'Товаришу, це моє сховище!', bubble_ratboss_bribed: 'Золото партії приймаю!',
    bubble_ratboss_defeated: 'Струна луснула…', bubble_ratboss_refuse: 'Пі! Мало!',
    bubble_speaker_intro: 'Засідання продовжується!', bubble_speaker_order: 'До порядку!',
    bubble_speaker_charge: 'Позбавити слова!', bubble_speaker_vote: 'Голосуємо! Всі проти нього!',
    bubble_speaker_bribed: 'Рішення прийнято… конструктивно.', bubble_speaker_defeated: 'Засідання… закрито…',
    bubble_speaker_refuse: 'Замало для регламенту!',
    bubble_journalist_stunned: 'Мій об’єктив!', bubble_detective_stunned: 'Це напад на НАБУ!',
    bubble_cop_stunned: 'Ай!',
    help_nut: 'кинути каштан (або «Капітал»)',
    help_chestnut: 'Каштан: оглушує ворога, боса — ранить. Трусіть каштани (E), шукайте на землі.',
    help_oldlady: 'Бабця: б’є палицею зблизька. Хабар (пенсія) — 45%.',
    help_kid: 'Малий: збирає каштани й кидається ними. Хабар — 70%.',
    help_book: '«Капітал» (у сховищі): важчий за каштан, оглушує довше.',
  },
  en: {
    drink_whiskey_pop: 'WHISKY!', drink_vodka_pop: 'VODKA!', shop_price: 'Price:', hint_shop: 'E — buy whisky',
    help_title_conscience: 'CONSCIENCE & ALCOHOL',
    help_conscience: 'Conscience (the gauge right of corruption): rises with bribes, bags and bad deeds. At 100 remorse paralyses you for a few seconds.',
    help_whiskey: 'Whisky: buy at a kiosk (E, 3 bribes) or find it. Conscience goes quiet, but you are drunk: slower, throws go astray.',
    help_vodka: 'Vodka (bunker): silences conscience almost completely. Legs tangle, the world sways.',
    help_voice: 'The inner voice comments on everything you do. The more the MP steals, the more cynical he sounds.',
    help_angel: 'The conscience angel: appears when remorse paralyses you.',
    hud_nuts: 'NUTS',
    ammo_nut: 'chestnut', ammo_book: '"Kapital"',
    no_nuts: 'No chestnuts! Shake a chestnut tree (E)',
    tree_empty: 'This tree is already bare',
    hint_tree: 'E — shake the chestnut tree',
    hint_secret: 'E — a secret hatch?!',
    secret_found: 'A SECRET PASSAGE TO THE BUNKER!',
    boss_animator: 'ANIMATOR IN A PATRON COSTUME', boss_ratboss: 'THE BALALAIKA RAT', boss_speaker: 'THE SPEAKER',
    boss_beaten: 'BOSS DEFEATED!', boss_bribed: 'THE BOSS… MADE A DEAL',
    goal_locked_animator: 'The animator blocks the door!',
    goal_locked_ratboss: 'The rat guards the exit!',
    goal_locked_speaker: 'The speaker has not closed the session!',
    level_p21: 'MARIINSKY PARK', level_p21b: 'THE BUNKER BELOW THE RADA', level_p22: 'RADA CORRIDORS', level_p23: 'THE SESSION HALL',
    sign_park: 'MARIINSKY PARK. DO NOT PICK THE CHESTNUTS!', sign_rada: 'ELECTED MEMBERS ONLY',
    sign_bunker: 'SHELTER No.1 (1953)', sign_corridor: 'QUIET! VOTING IN PROGRESS', sign_hall: 'SESSION HALL →',
    hurt_oldlady: 'Whacked with a walking stick!', hurt_chestnut: 'A chestnut to the head!', hurt_chocolate: 'Hit by a chocolate bar!',
    hurt_note: 'A sour note!', hurt_papers: 'Hit by a draft law!', hurt_shockwave: 'The gavel shockwave!',
    hurt_rat: 'Bitten by a rat!', hurt_oppmp: 'Shoved by the opposition!', hurt_animator: 'A Patron hug!',
    hurt_ratboss: 'Hit by a balalaika!', hurt_speaker: 'Crushed by the speaker!',
    bubble_oldlady_strike: 'You thief!', bubble_oldlady_bribed: 'For my pension… thank you, dear',
    bubble_oldlady_refuse: 'I can’t be bought!', bubble_oldlady_stunned: 'Oh my…',
    bubble_kid_mine: 'My chestnut!', bubble_kid_bribed: 'Yay, candy money!', bubble_kid_refuse: 'Not enough!',
    bubble_kid_stunned: 'Ow!',
    bubble_rat_bribed: 'Squeak! Party gold!', bubble_rat_refuse: 'Squeak!', bubble_rat_stunned: 'Squeak…',
    bubble_oppmp_throw: 'Shame!', bubble_oppmp_bribed: 'This is… for party needs',
    bubble_oppmp_refuse: 'I’m not like that!', bubble_oppmp_stunned: 'My ratings!',
    bubble_seatedmp_bribed: 'I vote yes!', bubble_seatedmp_refuse: 'Against!',
    bubble_assistant_hello: 'The MP is in a meeting…', bubble_assistant_bribed: 'I’ll pass it to the boss!',
    bubble_animator_intro: 'A photo with Patron — six bribes!', bubble_animator_beg: 'Woof! Chip in for dog food?',
    bubble_animator_bribed: 'Woof woof! Go on in!', bubble_animator_defeated: 'That’s it, my shift is over…',
    bubble_animator_refuse: 'Not enough for dog food!',
    bubble_ratboss_intro: 'Comrade, this is my shelter!', bubble_ratboss_bribed: 'Party gold accepted!',
    bubble_ratboss_defeated: 'The string snapped…', bubble_ratboss_refuse: 'Squeak! Not enough!',
    bubble_speaker_intro: 'The session continues!', bubble_speaker_order: 'Order!',
    bubble_speaker_charge: 'You lose the floor!', bubble_speaker_vote: 'Vote! Everyone against him!',
    bubble_speaker_bribed: 'Decision adopted… constructively.', bubble_speaker_defeated: 'The session… is closed…',
    bubble_speaker_refuse: 'Not enough for the rules of procedure!',
    bubble_journalist_stunned: 'My lens!', bubble_detective_stunned: 'That’s assault on NABU!',
    bubble_cop_stunned: 'Ow!',
    help_nut: 'throw a chestnut (or "Kapital")',
    help_chestnut: 'Chestnut: stuns enemies, hurts bosses. Shake chestnut trees (E), look on the ground.',
    help_oldlady: 'Old lady: whacks you with her stick up close. Bribe (pension) 45%.',
    help_kid: 'Kid: collects chestnuts and throws them at you. Bribe 70%.',
    help_book: '"Kapital" (bunker): heavier than a chestnut, stuns longer.',
  },
};
