// World 3 (the party, the block district, the railway station) and the endings. Merged in strings.js.
export const W3 = {
  uk: {
    cut_bridge: 'Міст через Дніпро будують дев’ятий рік. Кошторис переписували тричі, підрядник — кум міністра. Кажуть, цей міст тримає не кожного.',
    cut_bunker: 'Люк із червоною зіркою. Унизу пахне махоркою, архівом і чимось дуже радянським. Хтось грає на балалайці.',
    cut_corridor: 'Кулуари Верховної Ради. Тут вирішують більше, ніж у залі: журналісти чатують, опозиція шепоче, помічники носять папки. Головне — не зупинятися.',
    cut_hall: 'Сесійна зала. Голосують за бюджет — хтось своєю карткою, хтось чужою. Спікер уже підняв молоток.',
    end_epilogue: 'Кінець. Усі персонажі вигадані. Будь-які збіги з реальними депутатами — не випадкові, а закономірні.',
    choice_door_title: 'ВХІД ДО ВЕРХОВНОЇ РАДИ',
    choice_door_text: 'Парадні двері — повз охорону й журналістів. Або непримітні двері в підвал: кажуть, звідти можна пройти куди завгодно.',
    choice_door_front: 'ПАРАДНИЙ ВХІД', choice_door_basement: 'ДВЕРІ В ПІДВАЛ',
    choice_moral_title: 'ПОТЯГ НА ЗАХІД ЧИ НА СХІД?',
    choice_moral_text: 'На вокзалі два потяги. Один — до кордону, у тиху Європу. Інший — на схід, туди, де зараз вирішується доля країни.',
    choice_moral_west: 'НА ЗАХІД. Виїхати з країни', choice_moral_east: 'НА СХІД. Піти на фронт',
    end_front_1: 'Потяг на схід. Військкомат, черга добровольців: вчителі, трактористи, айтішники. І один депутат. Ніхто не просить автограф.',
    end_front_serve: 'Бліндаж, чай із термоса, кіт на колінах і побратими, які кличуть тебе «Бюджет». Страшно, брудно, чесно. Уперше в житті ти на своєму місці.',
    end_front_nabu: 'Двоє в плащах пробираються окопом, тримаючи папку над болотом: «Пане депутате, у нас до вас кілька запитань. Не зараз. Після перемоги».',
    end_front_court: 'Справа № 1-кп/…/2024 лежить на столі судді. Засідання відкладено до закінчення воєнного стану. Пил терпить. Правосуддя теж.',
    ending_front_serve: 'НА ФРОНТІ. НА СВОЄМУ МІСЦІ', ending_front_case: 'СПРАВА ЧЕКАЄ ПЕРЕМОГИ',
    end_moral_front: 'Хтось тікає, хтось іде захищати. Бюджет пам’ятає, хто що взяв. Країна пам’ятає, хто що віддав.',
    story_intro_3: 'Або… не бери нічого. Пройди весь шлях чистим — і народ тебе переобере.',
    level_e31: 'ВЕЧІРКА В ОЛІГАРХА', level_e32: 'СПАЛЬНИЙ РАЙОН. ЗОЛОТА ГОДИНА', level_e33: 'ЦЕНТРАЛЬНИЙ ВОКЗАЛ',
    world_3: 'СВІТ 3. ПАДІННЯ',
    story_w3: 'Світ 3. Падіння. Спікер переможений, і тебе запросили на вечірку, де вирішують усе. Там же все й закінчиться.',
    sign_villa: 'ВЕЧІРКА «ДЛЯ СВОЇХ»', sign_district: 'ТРОЄЩИНА. ЛАСКАВО ПРОСИМО', sign_station: 'КИЇВ-ПАСАЖИРСЬКИЙ',
    choice_mafia_title: 'ПРОПОЗИЦІЯ, ВІД ЯКОЇ НЕ ВІДМОВЛЯЮТЬСЯ',
    choice_mafia_text: 'Бос простягає валізу, повну доларів: «Один маленький закон — і це все твоє. Ну що, депутате, домовились?»',
    choice_mafia_yes: 'ТАК. Беру валізу', choice_mafia_no: 'НІ. Я не продаюся',
    cut_mafia_yes: 'УГОДА', cut_mafia_lost: 'ВІДМОВА', cut_mafia_won: 'ВІДМОВА', cut_taxi: 'ТАКСІ', cut_europe: 'КОРДОН',
    cut_yes_1: 'Валіза приємно важка. Бос плескає по плечу. Шампанське, ще шампанське, потім щось зелене в чарці…',
    cut_yes_2: 'Дві чарівні пані сміються з моїх жартів. Навіть з тих, що про бюджет. Останнє, що пам’ятаю, — їхні руки в моїй кишені. І в іншій. І на піджаку.',
    cut_wake_yes: 'Прокинувся на лавці. Спальний район, золота година. Ні піджака, ні грошей, ні валізи. Сорочка порвана. Бабця з балкона дивиться так, ніби знає все.',
    cut_lost_1: '«Не продаєшся?» — перепитав бос. Далі пам’ятаю тільки зірочки. Багато зірочок. І як хтось знімає з мене піджак — «на пам’ять».',
    cut_won_1: 'Я переміг боса мафії. Каштанами. Його хлопці так реготали, що забули мене добити. Але поки я святкував, хтось поцупив і піджак, і гаманець.',
    cut_wake_no: 'Прокинувся в спальному районі. Ні піджака, ні грошей. Зате совість чиста, а люди навколо — просто люди.',
    cut_taxi: 'Жовте таксі. Водій дивиться у дзеркало: «А ви часом не той депутат?» — «Ні, я його двійник. Бідніший». До вокзалу, будь ласка.',
    end_train_1: 'Потяг зупинився посеред поля. Двигун чхнув і затих. Провідниця знизує плечима: «Хтось вкрав гроші на ремонт локомотивів». Хтось. Цікаво хто.',
    end_nabu: 'Соняшники, захід сонця і двоє в плащах. «Пане депутате, ми вас зачекалися». Камери вже тут. Факти справді болять.',
    end_karma: 'Тиха ніч над полем. Тихий гул у небі. Шахед обрав одне купе. Твоє. Кажуть, це збіг. Кажуть, карма — теж збіг.',
    end_europe: 'Кордон позаду. Зелені пагорби, червоні дахи, синій прапор із зірками. Куди далі?',
    end_austria_happy: 'Австрія. Альпи, штрудель, балкон із видом на гори. Банк не ставить запитань. Поки що.',
    end_austria_mafia: 'Відень. Дощ, кав’ярня, чорне авто біля входу. Бос мафії не любить, коли його валізи відлітають без нього.',
    end_extradited: 'Місцева поліція була дуже ввічлива. Українські колеги — ще ввічливіші. Рейс до Києва — економ-класом. У наручниках.',
    end_abroad_happy: 'Вілла біля моря, новий паспорт, нове ім’я. Щоранку перевіряєш новини. Щовечора — замки на дверях.',
    choice_country_title: 'КУДИ ТІКАЄМО?', choice_country_text: 'Потяг перетнув кордон. Треба вирішити, де починати нове життя.',
    country_austria: 'АВСТРІЯ', country_poland: 'ПОЛЬЩА', country_spain: 'ІСПАНІЯ', country_portugal: 'ПОРТУГАЛІЯ',
    ending_train_nabu: 'ЗАТРИМАНО НАБУ. У ПОЛІ', ending_train_karma: 'КАРМА', ending_austria_happy: 'АЛЬПІЙСЬКА ПЕНСІЯ',
    ending_austria_mafia: 'МАФІЯ НЕ ПРОБАЧАЄ', ending_extradited: 'ЕКСТРАДИЦІЯ', ending_abroad_happy: 'ВТЕЧА (ПОКИ ЩО)',
    end_moral: 'Корупція завжди має наслідки. Не НАБУ — то карма. Не карма — то безсонні ночі. Бюджет пам’ятає все.',
    end_moral_honest: 'Жодної копійки. Виявляється, так теж можна. Чесність — найрідкісніша валюта в Раді. І найдорожча.',
    goal_locked_mafia: 'Бос хоче поговорити…', goal_locked_gopboss: 'Гопники перекрили дорогу до таксі!',
    boss_mafia: 'БОС МАФІЇ', boss_gopboss: 'ВАТАЖОК ГОПНИКІВ',
    taxi_salary: 'ТАКСІ — ЗА ЗАРПЛАТУ', taxi_need_money: 'Таксі — 5 $. Грошей нема!', train_need_ticket: 'Без квитка не пустять! Каса — на початку.',
    hint_ticket: 'E — купити квиток', ticket_bought: 'КВИТОК КУПЛЕНО', ticket_have: 'Квиток уже є',
    ticket_salary: 'ПРИЙШЛА ЗАРПЛАТА. КВИТОК ПЛАЦКАРТ',
    hurt_bandit: 'Бандит ударив!', hurt_mafia: 'Бос мафії ударив!', hurt_bottle: 'Пляшкою по голові!',
    hurt_egg: 'Яйцем в обличчя!', hurt_dog: 'Собака вкусив!', hurt_debris: 'Балкон на голову!', hurt_gopboss: 'Ватажок ударив!',
    bubble_bandit_friend: 'О, свій! Проходь.', bubble_bandit_angry: 'Ти хто такий, чесний?!', bubble_bandit_bribed: 'Нема питань.',
    bubble_bandit_refuse: 'Мало!', bubble_bandit_stunned: 'Ау…',
    bubble_mafia_offer: 'Депутате! Маю пропозицію…', bubble_mafia_deal: 'От і домовились. Гуляй!',
    bubble_mafia_intro: 'Ну тоді по-іншому…', bubble_mafia_defeated: 'Каштанами?! Мене?!',
    bubble_gopnik_bribed: 'На пиво — нормас.', bubble_gopnik_refuse: 'Е, мало!', bubble_gopnik_stunned: 'Шо?..',
    bubble_gopnik_gang: 'Братва, наших б’ють!',
    bubble_citizen_angry: 'Злодій! Тримай яйце!', bubble_citizen_calm: 'Добрий вечір!', bubble_citizen_bribed: 'Ну… дякую.',
    bubble_citizen_refuse: 'Засунь собі!', bubble_citizen_stunned: 'Ой!',
    bubble_dogwalker_angry: 'Фас його, Бобіку!', bubble_dogwalker_bribed: 'Бобік, фу.',
    bubble_gopboss_intro: 'Слиш, дядя. Мобілу дай подзвонити.', bubble_gopboss_bribed: 'О, так би й одразу.',
    bubble_gopboss_defeated: 'Все-все, ми пішли…', bubble_gopboss_refuse: 'Шо, все?',
    bubble_mp_stunned: 'Я депутат!',
  },
  en: {
    cut_bridge: 'The bridge over the Dnipro has been under construction for nine years. The budget was rewritten three times; the contractor is the minister’s godfather. They say this bridge doesn’t hold just anyone.',
    cut_bunker: 'A hatch with a red star. Down below it smells of cheap tobacco, old archives and something very Soviet. Someone is playing a balalaika.',
    cut_corridor: 'The lobbies of the Verkhovna Rada. More is decided here than in the hall: journalists lie in wait, the opposition whispers, assistants carry folders. The trick is to keep moving.',
    cut_hall: 'The session hall. The budget vote: some with their own card, some with a colleague’s. The Speaker has already raised his gavel.',
    end_epilogue: 'The end. All characters are fictional. Any resemblance to real MPs is not a coincidence — it is a pattern.',
    choice_door_title: 'ENTERING THE VERKHOVNA RADA',
    choice_door_text: 'The front door, past the guards and journalists. Or an inconspicuous basement door: they say you can get anywhere from there.',
    choice_door_front: 'THE FRONT DOOR', choice_door_basement: 'THE BASEMENT DOOR',
    choice_moral_title: 'THE TRAIN WEST OR THE TRAIN EAST?',
    choice_moral_text: 'Two trains at the station. One goes to the border and a quiet Europe. The other goes east, where the fate of the country is being decided.',
    choice_moral_west: 'WEST. Leave the country', choice_moral_east: 'EAST. Go to the front',
    end_front_1: 'The train east. A recruitment office, a queue of volunteers: teachers, tractor drivers, programmers. And one MP. Nobody asks for an autograph.',
    end_front_serve: 'A dugout, tea from a thermos, a cat on your lap and comrades who call you "Budget". Scary, dirty, honest. For the first time in your life you are where you belong.',
    end_front_nabu: 'Two men in trench coats make their way along the trench, holding a case file above the mud: "Sir, we have a few questions. Not now. After the victory."',
    end_front_court: 'Case No. 1-kp/…/2024 lies on the judge’s desk. The hearing is postponed until the end of martial law. The dust can wait. So can justice.',
    ending_front_serve: 'AT THE FRONT. WHERE YOU BELONG', ending_front_case: 'THE CASE WAITS FOR VICTORY',
    end_moral_front: 'Some run, some go to defend. The budget remembers who took what. The country remembers who gave what.',
    story_intro_3: 'Or… take nothing. Go the whole way clean and the people will re-elect you.',
    level_e31: 'THE OLIGARCH’S PARTY', level_e32: 'BLOCK DISTRICT. GOLDEN HOUR', level_e33: 'CENTRAL RAILWAY STATION',
    world_3: 'WORLD 3. THE FALL',
    story_w3: 'World 3. The fall. The Speaker is beaten, and you are invited to the party where everything is decided. That is also where everything ends.',
    sign_villa: 'PARTY "FRIENDS ONLY"', sign_district: 'TROIESHCHYNA. WELCOME', sign_station: 'KYIV-PASAZHYRSKYI',
    choice_mafia_title: 'AN OFFER YOU CAN’T REFUSE',
    choice_mafia_text: 'The boss holds out a briefcase full of dollars: "One little law and it is all yours. So, MP, do we have a deal?"',
    choice_mafia_yes: 'YES. Take the briefcase', choice_mafia_no: 'NO. I am not for sale',
    cut_mafia_yes: 'THE DEAL', cut_mafia_lost: 'THE REFUSAL', cut_mafia_won: 'THE REFUSAL', cut_taxi: 'TAXI', cut_europe: 'THE BORDER',
    cut_yes_1: 'The briefcase is pleasantly heavy. The boss pats my shoulder. Champagne, more champagne, then something green in a shot glass…',
    cut_yes_2: 'Two charming ladies laugh at my jokes. Even the ones about the budget. The last thing I remember is their hands in my pocket. And the other one. And on my jacket.',
    cut_wake_yes: 'I woke up on a bench. A block district, golden hour. No jacket, no money, no briefcase. A torn shirt. A granny on a balcony looks at me as if she knows everything.',
    cut_lost_1: '"Not for sale?" the boss asked again. After that I only remember stars. Lots of stars. And someone taking my jacket "as a souvenir".',
    cut_won_1: 'I beat the mafia boss. With chestnuts. His boys laughed so hard they forgot to finish me off. But while I celebrated, somebody took my jacket and my wallet.',
    cut_wake_no: 'I woke up in a block district. No jacket, no money. But a clear conscience, and the people around are just people.',
    cut_taxi: 'A yellow taxi. The driver looks in the mirror: "Aren’t you that MP?" — "No, I’m his double. A poorer one." To the station, please.',
    end_train_1: 'The train stopped in the middle of a field. The engine sneezed and died. The conductor shrugs: "Somebody stole the money for locomotive repairs." Somebody. I wonder who.',
    end_nabu: 'Sunflowers, a sunset and two men in trench coats. "Sir, we have been waiting for you." The cameras are already here. The facts really hurt.',
    end_karma: 'A quiet night over the field. A quiet hum in the sky. The Shahed chose one compartment. Yours. They say it was a coincidence. They say karma is a coincidence too.',
    end_europe: 'The border is behind. Green hills, red roofs, a blue flag with stars. Where to now?',
    end_austria_happy: 'Austria. The Alps, strudel, a balcony with a view of the mountains. The bank asks no questions. For now.',
    end_austria_mafia: 'Vienna. Rain, a café, a black car at the entrance. The mafia boss does not like it when his briefcases fly away without him.',
    end_extradited: 'The local police were very polite. The Ukrainian colleagues were even politer. A flight to Kyiv — economy class. In handcuffs.',
    end_abroad_happy: 'A villa by the sea, a new passport, a new name. Every morning you check the news. Every evening, the door locks.',
    choice_country_title: 'WHERE DO WE RUN?', choice_country_text: 'The train crossed the border. Time to decide where to start a new life.',
    country_austria: 'AUSTRIA', country_poland: 'POLAND', country_spain: 'SPAIN', country_portugal: 'PORTUGAL',
    ending_train_nabu: 'ARRESTED BY NABU. IN A FIELD', ending_train_karma: 'KARMA', ending_austria_happy: 'AN ALPINE RETIREMENT',
    ending_austria_mafia: 'THE MAFIA DOES NOT FORGIVE', ending_extradited: 'EXTRADITED', ending_abroad_happy: 'ESCAPED (FOR NOW)',
    end_moral: 'Corruption always has consequences. If not NABU, then karma. If not karma, then sleepless nights. The budget remembers everything.',
    end_moral_honest: 'Not a single coin. Turns out that is possible too. Honesty is the rarest currency in the Rada. And the most expensive one.',
    goal_locked_mafia: 'The boss wants a word…', goal_locked_gopboss: 'The gopniks block the way to the taxi!',
    boss_mafia: 'THE MAFIA BOSS', boss_gopboss: 'THE GOPNIK GANG LEADER',
    taxi_salary: 'TAXI — PAID FROM SALARY', taxi_need_money: 'Taxi — 5 $. No money!', train_need_ticket: 'No ticket, no train! The ticket office is at the start.',
    hint_ticket: 'E — buy a ticket', ticket_bought: 'TICKET BOUGHT', ticket_have: 'You already have a ticket',
    ticket_salary: 'SALARY ARRIVED. A THIRD-CLASS TICKET',
    hurt_bandit: 'Punched by a bandit!', hurt_mafia: 'Punched by the mafia boss!', hurt_bottle: 'A bottle to the head!',
    hurt_egg: 'An egg in the face!', hurt_dog: 'Bitten by a dog!', hurt_debris: 'A balcony on the head!', hurt_gopboss: 'Punched by the gang leader!',
    bubble_bandit_friend: 'Oh, one of ours! Go on.', bubble_bandit_angry: 'Who are you, Mr Honest?!', bubble_bandit_bribed: 'No questions.',
    bubble_bandit_refuse: 'Not enough!', bubble_bandit_stunned: 'Ow…',
    bubble_mafia_offer: 'MP! I have an offer…', bubble_mafia_deal: 'Deal. Now party!',
    bubble_mafia_intro: 'Then we do it the other way…', bubble_mafia_defeated: 'Chestnuts?! Me?!',
    bubble_gopnik_bribed: 'For a beer — fine.', bubble_gopnik_refuse: 'Hey, too little!', bubble_gopnik_stunned: 'Wha?..',
    bubble_gopnik_gang: 'Guys, they are beating ours!',
    bubble_citizen_angry: 'Thief! Have an egg!', bubble_citizen_calm: 'Good evening!', bubble_citizen_bribed: 'Well… thanks.',
    bubble_citizen_refuse: 'Keep it!', bubble_citizen_stunned: 'Oh!',
    bubble_dogwalker_angry: 'Get him, Bobik!', bubble_dogwalker_bribed: 'Bobik, leave it.',
    bubble_gopboss_intro: 'Hey, uncle. Lend me your phone.', bubble_gopboss_bribed: 'Should have started with that.',
    bubble_gopboss_defeated: 'Okay, okay, we are leaving…', bubble_gopboss_refuse: 'That’s it?',
    bubble_mp_stunned: 'I am an MP!',
  },
};
